#!/usr/bin/python3

import os
import subprocess

VAR_DIR = '/var/lib/graphite'

def initialized():
  if files := os.listdir(VAR_DIR):
    return any(
      os.path.getsize(os.path.join(VAR_DIR, f)) != 0
      for f in files
    )
  else:
    return False

def main():
  if not initialized():
    env = os.environ.copy()
    env['PYTHONPATH'] = '/opt/graphite/webapp'
    subprocess.check_call([
      'django-admin', 'migrate', '--settings=graphite.settings',
    ], env = env)

if __name__ == '__main__':
  main()
